# Generated by Django 3.1.7 on 2021-09-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Home_Electronics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=150)),
                ('item_name', models.CharField(max_length=150)),
                ('brand_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('item_weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('imageurl', models.URLField()),
                ('stock_availability', models.BooleanField()),
                ('quantity_in_stock', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery', to='products.category')),
            ],
            options={
                'ordering': ['-item_type'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=150)),
                ('publisher', models.CharField(max_length=150)),
                ('educational_field', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=13)),
                ('pages', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('item_weight', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('stock_availability', models.BooleanField()),
                ('quantity_in_stock', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'ordering': ['-educational_field'],
            },
        ),
        migrations.CreateModel(
            name='Body_Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_tag', models.CharField(max_length=10)),
                ('item_type', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('brand_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('item_weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('imageurl', models.URLField()),
                ('stock_availability', models.BooleanField()),
                ('quantity_in_stock', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'ordering': ['-item_type'],
            },
        ),
    ]
